molgenis/molgenis-py-bbmri-eric

- Jenkinsfile
- src/molgenis/bbmri_eric/eric.py
> Add TestPyPi to release flow

- Jenkinsfile
> Fix issues in release flow

- Jenkinsfile
- setup.cfg
> Improve release flow

- Jenkinsfile
> Undo formatting changes made by bumpversion & add comments

- Jenkinsfile
- bump-version.sh
> Put version bumping in separate file

- Jenkinsfile
- bump-version.sh
> fix: actually store new version from shell script

- Jenkinsfile
- README.md
> Run pre-commit in Jenkins buidls

- src/molgenis/bbmri_eric/_model.py
- src/molgenis/bbmri_eric/_stager.py
- src/molgenis/bbmri_eric/_validation.py
- src/molgenis/bbmri_eric/eric.py
- src/molgenis/bbmri_eric/nodes.py
> Refactoring & simplify validation

- Pipfile
- Pipfile.lock
- src/molgenis/bbmri_eric/_model.py
- src/molgenis/bbmri_eric/_publisher.py
- src/molgenis/bbmri_eric/_validation.py
- src/molgenis/bbmri_eric/bbmri_client.py
- src/molgenis/bbmri_eric/eric.py
> Deletion & Enrichment

- Pipfile.lock
- src/molgenis/bbmri_eric/_cli.py
- src/molgenis/bbmri_eric/_enrichment.py
- src/molgenis/bbmri_eric/_publisher.py
- src/molgenis/bbmri_eric/_stager.py
- src/molgenis/bbmri_eric/_validation.py
- src/molgenis/bbmri_eric/bbmri_client.py
- src/molgenis/bbmri_eric/dev.py
- src/molgenis/bbmri_eric/eric.py
- src/molgenis/bbmri_eric/errors.py
- src/molgenis/bbmri_eric/printer.py
> Output & error handling

- src/molgenis/bbmri_eric/_enrichment.py
- src/molgenis/bbmri_eric/_model.py
- src/molgenis/bbmri_eric/_publisher.py
- src/molgenis/bbmri_eric/_stager.py
- src/molgenis/bbmri_eric/_utils.py
- src/molgenis/bbmri_eric/_validation.py
- src/molgenis/bbmri_eric/bbmri_client.py
- src/molgenis/bbmri_eric/eric.py
- src/molgenis/bbmri_eric/errors.py
- src/molgenis/bbmri_eric/nodes.py
- src/molgenis/bbmri_eric/printer.py
> Add docstrings

- src/molgenis/bbmri_eric/bbmri_client.py
> feat: add methods to get single node

- CHANGELOG.md
> fix: changelog version

- CHANGELOG.md
- src/molgenis/bbmri_eric/cli.py
> Fix global error handling

- CHANGELOG.md
- setup.cfg
> Fix Python 3.6 compatibility

- Pipfile
- Pipfile.lock
> require development in 3.6

- CHANGELOG.md
- Pipfile.lock
- src/molgenis/bbmri_eric/model.py
> Fixes critical error when running on Python 3.6 (or lower)

- src/molgenis/bbmri_eric/bbmri_client.py
- src/molgenis/bbmri_eric/publisher.py
- tests/test_publisher.py
> Changes to solve the not deleting rows bug #36

- CHANGELOG.md
- src/molgenis/bbmri_eric/validation.py
- tests/test_validator.py
> Fix #42 Don't allow @ and . in identifiers

- CHANGELOG.md
- src/molgenis/bbmri_eric/validation.py
- tests/test_validator.py
> Fix #43 Only remove prefix if ID starts with prefix during validation

- setup.cfg
- sonar-project.properties
> fix: coverage reports

- src/molgenis/bbmri_eric/pid_service.py
> Fix PidService docstring

- CHANGELOG.md
- src/molgenis/bbmri_eric/enricher.py
- src/molgenis/bbmri_eric/model.py
- src/molgenis/bbmri_eric/printer.py
- src/molgenis/bbmri_eric/publisher.py
- src/molgenis/bbmri_eric/validation.py
- tests/test_enricher.py
- tests/test_model.py
- tests/test_validator.py
> Fix #35 & Fix #41: Issues around EU persons and networks

- README.md
- scripts/example.py
> doc: move readme code to example.py

- CHANGELOG.md
- scripts/example.py
- src/molgenis/bbmri_eric/eric.py
- src/molgenis/bbmri_eric/pid_manager.py
- src/molgenis/bbmri_eric/pid_service.py
- src/molgenis/bbmri_eric/publisher.py
- tests/test_pid_service.py
> fix: change pid format

- src/molgenis/bbmri_eric/enricher.py
> Fix: Set correct node code for EU rows

- CHANGELOG.md
- src/molgenis/bbmri_eric/pid_manager.py
- src/molgenis/bbmri_eric/pid_service.py
- src/molgenis/bbmri_eric/publisher.py
- tests/conftest.py
- tests/test_pid_manager.py
- tests/test_pid_service.py
> Feat: PID URLs are based on config parameter

- scripts/biobank_pid_assignment.py
> fix: add server_url to doc

- scripts/example.py
- src/molgenis/bbmri_eric/enricher.py
- src/molgenis/bbmri_eric/pid_manager.py
- src/molgenis/bbmri_eric/pid_service.py
- src/molgenis/bbmri_eric/publisher.py
- tests/test_pid_manager.py
- tests/test_pid_service.py
- tests/test_publisher.py
> feat: Feature toggle for the PIDs

- src/molgenis/bbmri_eric/publisher.py
- src/molgenis/bbmri_eric/transformer.py
- tests/test_publisher.py
- tests/test_transformer.py
- Functionality works & meets specifications
- Code unit/system tested
> refactor: rename Enricher to Transformer

- CHANGELOG.md
- src/molgenis/bbmri_eric/pid_service.py
- tests/test_pid_service.py
> feat: prefix PIDs with "1."

- CHANGELOG.md
- Pipfile.lock
- setup.cfg
- src/molgenis/bbmri_eric/bbmri_client.py
- src/molgenis/bbmri_eric/model.py
- src/molgenis/bbmri_eric/stager.py
- src/molgenis/bbmri_eric/utils.py
- tests/test_stager.py
- tests/test_utils.py
> Fix issue #61, import of NL data fails due to self-referencing columns

- .pre-commit-config.yaml
- Jenkinsfile
> chore: switch to pod template repository

- CHANGELOG.md
- src/molgenis/bbmri_eric/bbmri_client.py
- src/molgenis/bbmri_eric/transformer.py
- tests/test_transformer.py
> Merge 'covid19biobank' column into 'capabilities'

- scripts/hook.py
- src/molgenis/bbmri_eric/utils.py
> Post cross-restore hook

- scripts/hook.py
> fix: script crashes when successEmail or failureEmail are empty

- CHANGELOG.md
- src/molgenis/bbmri_eric/bbmri_client.py
- src/molgenis/bbmri_eric/categories.py
- src/molgenis/bbmri_eric/eric.py
- src/molgenis/bbmri_eric/model.py
- src/molgenis/bbmri_eric/publication_preparer.py
- src/molgenis/bbmri_eric/publisher.py
- src/molgenis/bbmri_eric/transformer.py
- src/molgenis/bbmri_eric/utils.py
- src/molgenis/bbmri_eric/validation.py
- tests/test_categories.py
- tests/test_eric.py
- tests/test_publisher.py
- tests/test_transformer.py
- tests/test_validator.py
> Collection categories

- scripts/sync_DE_qualities.py
> Qualities synchronisation script for German Directory

- src/molgenis/bbmri_eric/bbmri_client.py
- src/molgenis/bbmri_eric/model.py
- src/molgenis/bbmri_eric/transformer.py
- tests/test_publisher.py
- tests/test_transformer.py
> Automatically fill the 'combined quality' field in collections during publishing

- CHANGELOG.md
- src/molgenis/bbmri_eric/transformer.py
- tests/test_transformer.py
> Add method to fill the biobank_label of the collection

- .pre-commit-config.yaml
- Jenkinsfile
- Pipfile
- Pipfile.lock
- setup.cfg
> Migrate to Python 3.10

- Pipfile.lock
- scripts/hook.py
> feat: Add the update of Google Analytics settings to hook.py

- .pre-commit-config.yaml
- Pipfile
- Pipfile.lock
- setup.cfg
- src/molgenis/bbmri_eric/bbmri_client.py
- src/molgenis/bbmri_eric/eric.py
- src/molgenis/bbmri_eric/model.py
- src/molgenis/bbmri_eric/model_fitting.py
- src/molgenis/bbmri_eric/publication_preparer.py
- src/molgenis/bbmri_eric/stager.py
- src/molgenis/bbmri_eric/transformer.py
- src/molgenis/bbmri_eric/validation.py
- tests/conftest.py
- tests/resources/also_known.json
- tests/resources/biobanks.json
- tests/resources/collections.json
- tests/resources/networks.json
- tests/resources/persons.json
- tests/test_eric.py
- tests/test_model.py
- tests/test_model_fitting.py
- tests/test_publication_preparer.py
- tests/test_publisher.py
- tests/test_stager.py
- tests/test_transformer.py
- tests/test_validator.py
> BBMRI model changes part1 (a.o. also_known_in and head info to persons)

- Pipfile.lock
- scripts/biobank_pid_assignment.py
- scripts/example.py
- scripts/hook.py
- setup.cfg
- src/molgenis/bbmri_eric/bbmri_client.py
- src/molgenis/bbmri_eric/model.py
- src/molgenis/bbmri_eric/model_fitting.py
- src/molgenis/bbmri_eric/publisher.py
- src/molgenis/bbmri_eric/stager.py
- src/molgenis/bbmri_eric/utils.py
- tests/test_publisher.py
- tests/test_stager.py
- tests/test_utils.py
> Remove methods that are moved to molgenis-py-client and refine warnings

- CHANGELOG.md
- src/molgenis/bbmri_eric/model.py
- src/molgenis/bbmri_eric/validation.py
- tests/conftest.py
- tests/resources/biobanks.json
- tests/test_validator.py
> Hyperlink validation added

- .pre-commit-config.yaml
- CHANGELOG.md
- scripts/hook.py
- src/molgenis/bbmri_eric/bbmri_client.py
- src/molgenis/bbmri_eric/model.py
- src/molgenis/bbmri_eric/transformer.py
- tests/conftest.py
- tests/test_eric.py
- tests/test_errors.py
- tests/test_model.py
- tests/test_printer.py
- tests/test_stager.py
- tests/test_transformer.py
> Add withdrawn column and update hook script

- CHANGELOG.md
- src/molgenis/bbmri_eric/bbmri_client.py
- src/molgenis/bbmri_eric/eric.py
- src/molgenis/bbmri_eric/model.py
- tests/conftest.py
- tests/resources/facts.json
- tests/test_model.py
- tests/test_publisher.py
- tests/test_stager.py
- tests/test_validator.py
> feat: include publishing of Facts

- CHANGELOG.md
- src/molgenis/bbmri_eric/bbmri_client.py
- src/molgenis/bbmri_eric/categories.py
- src/molgenis/bbmri_eric/eric.py
- src/molgenis/bbmri_eric/model.py
- tests/conftest.py
- tests/test_categories.py
- tests/test_model.py
- tests/test_printer.py
- tests/test_stager.py
> feat: map matching disease codes to categories

- CHANGELOG.md
- src/molgenis/bbmri_eric/eric.py
- tests/test_categories.py
> feat: change matching_attrs to exact_ and ntbt_mapping

- CHANGELOG.md
- src/molgenis/bbmri_eric/publisher.py
> Fix issue #68, deleting biobanks with no PID fails

- CHANGELOG.md
- scripts/example.py
- src/molgenis/bbmri_eric/bbmri_client.py
- src/molgenis/bbmri_eric/model.py
- src/molgenis/bbmri_eric/pid_manager.py
- src/molgenis/bbmri_eric/stager.py
- tests/test_stager.py
> feat: get staged and not the published data from an external server

- .circleci/config.yml
> fix: get git push to work

- .circleci/config.yml
> chore: remove config step

- .circleci/config.yml
> chore: update git config

- .circleci/config.yml
> chore: add molgenis-jenkins user to git config

- CHANGELOG.md
- src/molgenis/bbmri_eric/categories.py
- tests/test_categories.py
> feat: add new categories
